<a href="https://colab.research.google.com/github/Mirza-Hafiz-Baig/rainfall_game/blob/vedant-game-updates/rainfall_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

Saving rainfall in india 1901-2015.csv to rainfall in india 1901-2015.csv

In [2]:
df = pd.read_csv("rainfall in india 1901-2015.csv")

df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [3]:
months = [
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
    "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"
]

df.columns = df.columns.str.strip()
df["SUBDIVISION"] = df["SUBDIVISION"].str.strip()

# Calculate total rainfall for each year
df["ANNUAL_RAINFALL"] = df[months].sum(axis=1, min_count=1)

# Average annual rainfall for each region
regional_rainfall = (
    df.groupby("SUBDIVISION")["ANNUAL_RAINFALL"]
      .mean()
      .sort_values(ascending=False)
)

print("Top 10 regions by average annual rainfall:")
display(regional_rainfall.head(10).to_frame())

print("\nOverall average annual rainfall:")
print(round(df["ANNUAL_RAINFALL"].mean(), 2), "mm")

Top 10 regions by average annual rainfall:

                                    ANNUAL_RAINFALL
SUBDIVISION
ARUNACHAL PRADESH                       3414.786598
COASTAL KARNATAKA                       3405.900000
KONKAN & GOA                            2977.677391
KERALA                                  2925.499130
ANDAMAN & NICOBAR ISLANDS               2876.093636
SUB HIMALAYAN WEST BENGAL & SIKKIM      2752.203478
ASSAM & MEGHALAYA                       2580.698261
NAGA MANI MIZO TRIPURA                  2433.638261
LAKSHADWEEP                             1561.094737
GANGETIC WEST BENGAL                    1490.493913

Overall average annual rainfall:
1414.38 mm